services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./data/storage:/var/www/html/storage/app/public
      - ./data/database.sqlite:/var/www/html/database/database.sqlite
    restart: unless-stopped
